# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzyDqxA0GLfwHn5VxJbLK65aljrkg5CL
"""

import numpy as np

# 1. massiv yaratish
olma = np.array([1,2,3,4,5])
nok =np.array([[1,2,3],[4,5,6]])

# 2. matematik yaratish
qoshish=np.sum(olma)
ortacha=np.mean(olma)
kop=np.prod(olma)
qoshish1 =np.sum(nok)
ortacha1 =np.mean(nok)
kop1 =np.prod(nok)
print("olma masivi ", olma )
print("nok:\2",nok )

print("massivlar yegindisi",qoshish)
print("massivlar ortachasi",ortacha)
print("massivlar kopaytmasi",kop)

print("massivlar yegindisi",qoshish1)
print("massivlar ortacha ",ortacha1)
print("massivlar kopaytma ",kop1)


import pandas as pd

#1 . DataFream yaratish
data={
    'ism ': ['ali','vali','gani','ayubxon','bunyod','farrux','hakim','anvarjon','eldor','dilyor'],
    'yosh': [19,25,16,19,19,24,95,16,15,40],
    'shahar': ['Toshkent','fargona','samarqand','fargona','fargona','Toshkent','fargona','samarqand','fargona','fargona'],
}
df=pd.DataFrame(data)

# 2. malumotlarni korish
print(df)

# 3,filtirlash
young_people=df[df['yosh']<40]
print("40 yoshdan kichiklarni :\n",young_people)

#4 ozgartirish
df['yosh']+=1 #har  bir shahsni 1ga qosh
print("yangilanga data fream:\n",df)

#5 fargonaliklar chiqsin
city=df[df['shahar']=='fargona']
print("fargona shahrdegilar chiqarilar",city)